### ISSUE TITLE
[QA] 지도 첫 진입 시  "우선 강남지역만 서비스중이에요!" ToastView 표출

### ISSUE THREAD

**Issue by NewHooon** [YAPP-Github/Coffice-iOS#240]
# 🔍 Issue

- [ ]  지도 첫 진입 시  "우선 강남지역만 서비스중이에요!" ToastView 표출

**Comment by applebuddy** [comment]
이미 맵뷰에 사용되는 토스트 뷰가 있는걸로 아는데(북마크 완료 시) 재사용 할수있는지 고민해봐도 좋을것같아요~

**Comment by NewHooon** [comment]
> @NewHooon 이미 맵뷰에 사용되는 토스트 뷰가 있는걸로 아는데(북마크 완료 시) 재사용 할수있는지 고민해봐도 좋을것같아요.

형식이 많이 달라서 재사용하기에 어려움이 있을 것 같습니다.
<img width="142" alt="image" src="https://github.com/YAPP-Github/Coffice-iOS/assets/108966759/7cfc507a-d64d-42a1-b643-c8dbfd79e3a9">  <img width="140" alt="image" src="https://github.com/YAPP-Github/Coffice-iOS/assets/108966759/d5811570-cc3d-4dec-a4a3-3d3770e5d18f">
