### ISSUE TITLE
[Chore] 클러스터 마커 구현

### ISSUE THREAD

**Issue by hanjaesueng** [YAPP-Github/Coffice-iOS#349]
## 🧹 Chore

맵 줌아웃시에 클러스터 마커로 합쳐지는 기능 구현 필요

### Issue 재현 경로를 설명해주세요.

1. 네이버 맵 줌 인/ 줌 아웃
2. 클러스터 마커 확인

### 수정 후 예상되는 동작을 설명해주세요.
줌 인/ 줌 아웃 시에 클러스터 마커 생성 및 해제

**Comment by applebuddy** [comment]
Jira 카드로 이관합니다!
